// <auto-generated />
using System;
using Editoria.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Editoria.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Editoria.Models.Entities.Advertisement", b =>
                {
                    b.Property<int>("AdvertisementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvertisementId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdvertisementId");

                    b.HasIndex("IssueId");

                    b.ToTable("Advertisements");

                    b.HasData(
                        new
                        {
                            AdvertisementId = 1,
                            Cost = 100.50m,
                            IssueId = 1,
                            Text = "Скидка 50% на все товары! Только сегодня.",
                            Type = "Баннер"
                        },
                        new
                        {
                            AdvertisementId = 2,
                            Cost = 200.00m,
                            IssueId = 1,
                            Text = "Подпишитесь на нашу рассылку и получите подарок!",
                            Type = "Всплывающее окно"
                        },
                        new
                        {
                            AdvertisementId = 3,
                            Cost = 500.00m,
                            IssueId = 2,
                            Text = "Откройте для себя мир новых возможностей с нашим продуктом.",
                            Type = "Видео"
                        },
                        new
                        {
                            AdvertisementId = 4,
                            Cost = 50.00m,
                            IssueId = 2,
                            Text = "Купите сейчас и получите бесплатную доставку.",
                            Type = "Текст"
                        },
                        new
                        {
                            AdvertisementId = 5,
                            Cost = 120.00m,
                            IssueId = 3,
                            Text = "Лучшие предложения дня — не пропустите!",
                            Type = "Боковая панель"
                        },
                        new
                        {
                            AdvertisementId = 6,
                            Cost = 1000.00m,
                            IssueId = 3,
                            Text = "Эксклюзивное предложение! Только для первых 100 клиентов.",
                            Type = "На всю страницу"
                        },
                        new
                        {
                            AdvertisementId = 7,
                            Cost = 150.75m,
                            IssueId = 4,
                            Text = "Успейте купить! Акция заканчивается через 3 дня.",
                            Type = "Баннер"
                        });
                });

            modelBuilder.Entity("Editoria.Models.Entities.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArticleId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IssueId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            IssueId = 1,
                            PublicationDate = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Dota 2 — это одна из самых популярных многопользовательских онлайн-игр, разработанная и выпущенная компанией Valve. Игра является продолжением модификации Defense of the Ancients (DotA) для Warcraft III, которая в свою очередь была создана фанатами. В Dota 2 игроки управляют героями с уникальными способностями, сражаясь друг с другом в командных боях на аренах. С момента своего выпуска в 2013 году, игра приобрела огромную популярность благодаря своим глубоко проработанным механикам, регулярным обновлениям и мировой киберспортивной сцене. Чемпионаты, такие как The International, привлекли внимание зрителей со всего мира и сделали Dota 2 одной из самых зрелищных и высокооплачиваемых игр в истории киберспорта.",
                            Title = "Dota 2: История и эволюция игры"
                        },
                        new
                        {
                            ArticleId = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            IssueId = 1,
                            PublicationDate = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Наруто — это культовое японское аниме, которое стало знаковым не только для поклонников японской культуры, но и для широкой аудитории по всему миру. История рассказывает о мальчике по имени Наруто Узумаке, который мечтает стать Хокаге, сильнейшим ниндзя своей деревни. Сюжет не только захватывает своим экшеном, но и затрагивает важные философские вопросы, такие как борьба за признание, ценность дружбы и преданности, а также то, что настоящая сила заключается не в физической мощи, а в решимости идти вперёд, несмотря на трудности. Аниме также прекрасно сочетает элементы боевых искусств и магии, что делает его одним из самых успешных проектов в истории японской анимации.",
                            Title = "Наруто: Путь Ниндзя и философия силы"
                        },
                        new
                        {
                            ArticleId = 3,
                            AuthorId = 3,
                            CategoryId = 3,
                            IssueId = 2,
                            PublicationDate = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "C# (C-Sharp) — это объектно-ориентированный язык программирования, разработанный компанией Microsoft. Он является частью .NET Framework и используется для разработки различных приложений: от десктопных до мобильных и веб-приложений. C# сочетает в себе простоту и мощь, что делает его отличным выбором как для новичков, так и для опытных разработчиков. Основные особенности языка — это строгая типизация, поддержка параллельных вычислений, обработка исключений и богатая стандартная библиотека. C# активно используется в разработке игр (через Unity), а также в построении масштабируемых веб-приложений с использованием ASP.NET Core.",
                            Title = "C# для начинающих: Основы языка программирования"
                        },
                        new
                        {
                            ArticleId = 4,
                            AuthorId = 4,
                            CategoryId = 1,
                            IssueId = 2,
                            PublicationDate = new DateTime(2024, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "React — это библиотека JavaScript, разработанная Facebook для создания пользовательских интерфейсов. Она позволяет строить веб-приложения с динамическими и интерактивными интерфейсами, обновляя только те части страницы, которые изменяются. React использует концепцию виртуального DOM, что позволяет значительно улучшить производительность при изменении данных. Библиотека также поддерживает компонентный подход, где каждый элемент интерфейса является независимым компонентом, который можно повторно использовать и тестировать. React является популярным выбором для разработки сложных одностраничных приложений (SPA), и используется в таких крупных проектах, как Facebook, Instagram и WhatsApp.",
                            Title = "React: Введение в библиотеку для создания интерфейсов"
                        },
                        new
                        {
                            ArticleId = 5,
                            AuthorId = 5,
                            CategoryId = 2,
                            IssueId = 3,
                            PublicationDate = new DateTime(2024, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Unity — это одна из самых популярных платформ для разработки игр. С её помощью можно создавать игры как для мобильных устройств, так и для ПК, консолей и VR-устройств. Unity имеет мощный визуальный редактор, позволяющий быстро прототипировать игровые механики, а также использовать готовые ассеты и ресурсы из Unity Asset Store. Для создания игры не нужно быть опытным программистом — базовые знания о том, как работают игровые движки, и понимание принципов геймдизайна будут полезны для начала. Unity поддерживает множество языков программирования, но C# является основным для разработки в этом движке, что делает его отличным выбором для начинающих разработчиков игр.",
                            Title = "Как сделать свою первую игру с использованием Unity"
                        },
                        new
                        {
                            ArticleId = 6,
                            AuthorId = 6,
                            CategoryId = 1,
                            IssueId = 3,
                            PublicationDate = new DateTime(2024, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Counter-Strike 2 — это продолжение культовой серии шутеров от первого лица, которая оказала значительное влияние на жанр многопользовательских игр. В новой версии, выпущенной после успешной первой игры и её многочисленных обновлений, игроки снова встают на одну из сторон — террористов или антитеррористов — и сражаются друг с другом в напряженных матчах. Главным новшеством является улучшенная графика и физика игры, а также новые карты, оружие и режимы. Counter-Strike 2 продолжает поддерживать активное сообщество игроков и киберспортивные турниры, такие как ESL и BLAST Premier, привлекая игроков со всего мира. Игра сочетает в себе динамичность, тактический подход и командную работу, что делает её одной из самых популярных многопользовательских игр в истории.",
                            Title = "Counter-Strike 2: Революция в игровом процессе"
                        },
                        new
                        {
                            ArticleId = 7,
                            AuthorId = 7,
                            CategoryId = 1,
                            IssueId = 4,
                            PublicationDate = new DateTime(2024, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Detroit: Become Human — это интерактивная драма и приключенческая игра, разработанная студией Quantic Dream. Игра разворачивается в будущем, где андроиды начинают обретать сознание и задаваться вопросами о своей роли в обществе. История фокусируется на трёх персонажах: андроиде-слуге Каре, андроиде-полицейском Конноре и андроиде-революционере Маркусе, которые оказываются втянутыми в борьбу за свободу и равенство. В игре принимаются важнейшие моральные решения, которые влияют на развитие событий, что делает каждый проход уникальным. Визуальный стиль игры впечатляет, а сюжет задаёт вопросы о природе человечности, моральных дилеммах и том, как мы относимся к технологиям, которые создаём.",
                            Title = "Detroit: Become Human — наше будущее будущее"
                        });
                });

            modelBuilder.Entity("Editoria.Models.Entities.ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTags");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            TagId = 1
                        },
                        new
                        {
                            ArticleId = 1,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 2,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 3,
                            TagId = 4
                        },
                        new
                        {
                            ArticleId = 4,
                            TagId = 1
                        },
                        new
                        {
                            ArticleId = 4,
                            TagId = 5
                        },
                        new
                        {
                            ArticleId = 5,
                            TagId = 3
                        },
                        new
                        {
                            ArticleId = 6,
                            TagId = 2
                        },
                        new
                        {
                            ArticleId = 7,
                            TagId = 4
                        });
                });

            modelBuilder.Entity("Editoria.Models.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Email = "alexey.ivanov@example.com",
                            Name = "Алексей",
                            Phone = "123-456-7890",
                            Surname = "Иванов"
                        },
                        new
                        {
                            AuthorId = 2,
                            Email = "maria.petrova@example.com",
                            Name = "Мария",
                            Phone = "234-567-8901",
                            Surname = "Петрова"
                        },
                        new
                        {
                            AuthorId = 3,
                            Email = "ivan.sidorov@example.com",
                            Name = "Иван",
                            Phone = "345-678-9012",
                            Surname = "Сидоров"
                        },
                        new
                        {
                            AuthorId = 4,
                            Email = "elena.kuznetsova@example.com",
                            Name = "Елена",
                            Phone = "456-789-0123",
                            Surname = "Кузнецова"
                        },
                        new
                        {
                            AuthorId = 5,
                            Email = "dmitry.smirnov@example.com",
                            Name = "Дмитрий",
                            Phone = "567-890-1234",
                            Surname = "Смирнов"
                        },
                        new
                        {
                            AuthorId = 6,
                            Email = "olga.fedorova@example.com",
                            Name = "Ольга",
                            Phone = "678-901-2345",
                            Surname = "Фёдорова"
                        },
                        new
                        {
                            AuthorId = 7,
                            Email = "sergey.mikhailov@example.com",
                            Name = "Сергей",
                            Phone = "789-012-3456",
                            Surname = "Михайлов"
                        });
                });

            modelBuilder.Entity("Editoria.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Новости о политике",
                            Name = "Политика"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Новости экономики и финансов",
                            Name = "Экономика"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Новости о культуре и искусстве",
                            Name = "Культура"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Спортивные события и новости",
                            Name = "Спорт"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Новости технологий и инноваций",
                            Name = "Технологии"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "Новости о здоровье и медицинских исследованиях",
                            Name = "Здоровье"
                        },
                        new
                        {
                            CategoryId = 7,
                            Description = "Новости образования и науки",
                            Name = "Образование"
                        });
                });

            modelBuilder.Entity("Editoria.Models.Entities.Editor", b =>
                {
                    b.Property<int>("EditorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EditorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EditorId");

                    b.ToTable("Editors");

                    b.HasData(
                        new
                        {
                            EditorId = 1,
                            Email = "anna.ivanova@example.com",
                            Name = "Анна",
                            Surname = "Иванова"
                        },
                        new
                        {
                            EditorId = 2,
                            Email = "boris.smirnov@example.com",
                            Name = "Борис",
                            Surname = "Смирнов"
                        },
                        new
                        {
                            EditorId = 3,
                            Email = "victor.kuznetsov@example.com",
                            Name = "Виктор",
                            Surname = "Кузнецов"
                        },
                        new
                        {
                            EditorId = 4,
                            Email = "galina.petrova@example.com",
                            Name = "Галина",
                            Surname = "Петрова"
                        },
                        new
                        {
                            EditorId = 5,
                            Email = "dmitriy.sidorov@example.com",
                            Name = "Дмитрий",
                            Surname = "Сидоров"
                        },
                        new
                        {
                            EditorId = 6,
                            Email = "ekaterina.soboleva@example.com",
                            Name = "Екатерина",
                            Surname = "Соболева"
                        },
                        new
                        {
                            EditorId = 7,
                            Email = "zhanna.nikolaeva@example.com",
                            Name = "Жанна",
                            Surname = "Николаева"
                        });
                });

            modelBuilder.Entity("Editoria.Models.Entities.Issue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NewspaperId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IssueId");

                    b.HasIndex("NewspaperId");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            IssueId = 1,
                            Content = "Новости Москвы",
                            NewspaperId = 1,
                            PublicationDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IssueId = 2,
                            Content = "Обзор бизнеса",
                            NewspaperId = 2,
                            PublicationDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IssueId = 3,
                            Content = "Новые технологии",
                            NewspaperId = 3,
                            PublicationDate = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IssueId = 4,
                            Content = "Новости села",
                            NewspaperId = 4,
                            PublicationDate = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IssueId = 5,
                            Content = "Искусство и культура",
                            NewspaperId = 5,
                            PublicationDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IssueId = 6,
                            Content = "Научные открытия",
                            NewspaperId = 6,
                            PublicationDate = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IssueId = 7,
                            Content = "Спортивные события",
                            NewspaperId = 7,
                            PublicationDate = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Editoria.Models.Entities.Newspaper", b =>
                {
                    b.Property<int>("NewspaperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewspaperId"));

                    b.Property<int>("Circulation")
                        .HasColumnType("int");

                    b.Property<int>("EditorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewspaperId");

                    b.HasIndex("EditorId")
                        .IsUnique();

                    b.ToTable("Newspapers");

                    b.HasData(
                        new
                        {
                            NewspaperId = 1,
                            Circulation = 10000,
                            EditorId = 1,
                            Name = "Городские новости",
                            Region = "Москва",
                            Type = "Ежедневная"
                        },
                        new
                        {
                            NewspaperId = 2,
                            Circulation = 5000,
                            EditorId = 2,
                            Name = "Бизнес-обозрение",
                            Region = "Санкт-Петербург",
                            Type = "Еженедельная"
                        },
                        new
                        {
                            NewspaperId = 3,
                            Circulation = 7000,
                            EditorId = 3,
                            Name = "Технологический вестник",
                            Region = "Новосибирск",
                            Type = "Ежемесячная"
                        },
                        new
                        {
                            NewspaperId = 4,
                            Circulation = 3000,
                            EditorId = 4,
                            Name = "Сельская жизнь",
                            Region = "Краснодар",
                            Type = "Еженедельная"
                        },
                        new
                        {
                            NewspaperId = 5,
                            Circulation = 4000,
                            EditorId = 5,
                            Name = "Культура и искусство",
                            Region = "Казань",
                            Type = "Ежемесячная"
                        },
                        new
                        {
                            NewspaperId = 6,
                            Circulation = 6000,
                            EditorId = 6,
                            Name = "Наука сегодня",
                            Region = "Екатеринбург",
                            Type = "Ежемесячная"
                        },
                        new
                        {
                            NewspaperId = 7,
                            Circulation = 8000,
                            EditorId = 7,
                            Name = "Мир спорта",
                            Region = "Сочи",
                            Type = "Еженедельная"
                        });
                });

            modelBuilder.Entity("Editoria.Models.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Description = "Все, что связано с кодированием, языками программирования и разработкой ПО",
                            Name = "Программирование"
                        },
                        new
                        {
                            TagId = 2,
                            Description = "Научные достижения, открытия и исследования",
                            Name = "Наука"
                        },
                        new
                        {
                            TagId = 3,
                            Description = "Советы по здоровью, медицина и здоровый образ жизни",
                            Name = "Здоровье"
                        },
                        new
                        {
                            TagId = 4,
                            Description = "Предпринимательство, управление и финансы",
                            Name = "Бизнес"
                        },
                        new
                        {
                            TagId = 5,
                            Description = "Учеба, курсы, саморазвитие и обучение",
                            Name = "Образование"
                        });
                });

            modelBuilder.Entity("Editoria.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Editoria.Models.Entities.Advertisement", b =>
                {
                    b.HasOne("Editoria.Models.Entities.Issue", "Issue")
                        .WithMany("Advertisements")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Editoria.Models.Entities.Article", b =>
                {
                    b.HasOne("Editoria.Models.Entities.Author", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Editoria.Models.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Editoria.Models.Entities.Issue", "Issue")
                        .WithMany("Articles")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Editoria.Models.Entities.ArticleTag", b =>
                {
                    b.HasOne("Editoria.Models.Entities.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Editoria.Models.Entities.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Editoria.Models.Entities.Issue", b =>
                {
                    b.HasOne("Editoria.Models.Entities.Newspaper", "Newspaper")
                        .WithMany("Issues")
                        .HasForeignKey("NewspaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Newspaper");
                });

            modelBuilder.Entity("Editoria.Models.Entities.Newspaper", b =>
                {
                    b.HasOne("Editoria.Models.Entities.Editor", "Editor")
                        .WithOne("Newspaper")
                        .HasForeignKey("Editoria.Models.Entities.Newspaper", "EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editor");
                });

            modelBuilder.Entity("Editoria.Models.Entities.Article", b =>
                {
                    b.Navigation("ArticleTags");
                });

            modelBuilder.Entity("Editoria.Models.Entities.Author", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Editoria.Models.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Editoria.Models.Entities.Editor", b =>
                {
                    b.Navigation("Newspaper")
                        .IsRequired();
                });

            modelBuilder.Entity("Editoria.Models.Entities.Issue", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Editoria.Models.Entities.Newspaper", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("Editoria.Models.Entities.Tag", b =>
                {
                    b.Navigation("ArticleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
